FROM amazonlinux:2.0.20200406.0

WORKDIR /app

RUN yum install -y zip yum-utils rpmdevtools \
    python3 python3-pip texlive-latex texlive-latex-bin \
    texlive-latex-bin-bin texlive-latex-fonts && \
    yum clean all

RUN mkdir -p downloads/packages/{bin,lib} && yumdownloader --destdir downloads \
    texlive-latex texlive-latex-bin texlive-latex-bin-bin texlive-latex-fonts

RUN rpmdev-extract -C downloads/packages downloads/*rpm && \
    cp -a downloads/packages/*/usr/bin/* downloads/packages/bin && \
    cp -a downloads/packages/*/usr/lib64/* downloads/packages/lib && \
    cd downloads/packages && zip -r9 packages.zip bin lib

#RUN mkdir -p downloads/packages/lib && cd downloads && \
#    cp -a
#
#RUN zip -r9 packages.zip downloads/*/usr/lib64/*


#RUN apt-get update && apt-get install -y python3 python3-pip
#RUN python3.8 -m pip install --upgrade pip && \
#    python3.8 -m pip install pipenv
#
##COPY Pipfile Pipfile.lock /app/
#RUN pwd && ls -asl .
#RUN pipenv install --system --deploy --ignore-pipfile
#RUN echo `pipenv --venv`
#
##COPY . /app/
#
##RUN ./bundle.sh
